In [ ]:
import numpy as np
np.__version__

'1.19.5'

En `NumPy` el objeto básico se trata de una lista multidimensional de números normalmente del mismo tipo.

In [ ]:
p = np.array([1, 2, 3])
p

array([1, 2, 3])

In [ ]:
type(p)

numpy.ndarray

In [ ]:
# podemos llamar los elementos por posición
p[0]

1

En Numpy, a las dimensiones se les conoce con el nombre de ejes (axes) y el número de los ejes, rango (rank).

Array es un alias para referirse al tipo de objeto numpy.ndarray

In [ ]:
# ndarray.ndim : el número de ejes del objeto array (matriz)
a = np.arange(3*2) # con esta función creamos la estructura unidimensional de 6 elementos
print("Array o matriz unidimensional")
print(a)

Array o matriz unidimensional
[0 1 2 3 4 5]


In [ ]:
a.shape

(6,)

In [ ]:
a.ndim

1

In [ ]:
# Para convertirla en matriz 3x2
b = a.reshape(3,2)
print("Matriz 3x2")
print(b)

Matriz 3x2
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
# Realizamos el slice:dice de nuestra matriz
b[0] # devuelve por posición 0, la fila 0 que incluye los elementos (0,1)

array([0, 1])

In [ ]:
b[1,1] # extraemos de la fila 2, columna 2 (índices 1,1), el elemento 3

3

In [ ]:
type(b[1,1]) # devuelve el tipo de elemento de nuestra matriz

numpy.int64

In [ ]:
b.size # devuelve el número de elementos

6

> Podemos crear un array de ceros.

In [ ]:
z = np.zeros(10) # utilizamos la función np.zeros para crear un vector de ceros
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
# Podemos cambiar cualquiera de los valores accediendo por su posición
z[4] = 5. # 5. es el equivalente de 5.0
z[-1] = .1 # es lo mismo que 0.1
print(z)

[0.  0.  0.  0.  5.  0.  0.  0.  0.  0.1]


In [18]:
type(z)

numpy.ndarray

In [19]:
type(z[-1])

numpy.float64

In [20]:
a

array([0, 1, 2, 3, 4, 5])

In [21]:
a = np.arange(10,20) # incluimos el elemento start=10, hasta el stop=20-1
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
# si queremos añadir el paso a nuestra función arange
a = np.arange(10,20,2)
a

array([10, 12, 14, 16, 18])

In [24]:
# Otra forma de crear los arrays
c = np.array([
              [1,2,3], 
              [4,5,6]
              ])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
# Es equivalente crear dos listas en Python y luego nuestro ndarray
lista_1 = [7,8,9]
lista_2 = [0.1, 0.2, 0.3]
d = np.array([
              lista_1,
              lista_2
])

In [26]:
d

array([[7. , 8. , 9. ],
       [0.1, 0.2, 0.3]])

## Operaciones con matrices

Con **numpy** podemos implementar todas las operaciones habituales con matrices

In [27]:
# construimos dos matrices
A = np.array([
              [1,0],
              [0,1]
])

B = np.array([
              [1,2],
              [3,4]
])

C = np.array([
              [1,5],
              [6,4],
              [8,9]
])

In [28]:
type(A)

numpy.ndarray

In [32]:
print(A.ndim)
print(B.ndim)
print(C.ndim)

2
2
2


In [33]:
print(A.shape)
print(B.shape)
print(C.shape)

(2, 2)
(2, 2)
(3, 2)


In [34]:
A

array([[1, 0],
       [0, 1]])

In [35]:
B

array([[1, 2],
       [3, 4]])

In [36]:
# suma de matrices
print(A+B)

[[2 2]
 [3 5]]


In [37]:
print(B+C)

ValueError: ignored

In [38]:
# Resta de matrices
print(B-C)

ValueError: ignored

In [39]:
print(A-B)

[[ 0 -2]
 [-3 -3]]


In [40]:
# multiplicación de matrices
print(A*B) # elemento por elemento

[[1 0]
 [0 4]]


In [41]:
# producto de matriz por matriz
print(A.dot(B))

[[1 2]
 [3 4]]


In [42]:
# potencias 
print(B**2)

[[ 1  4]
 [ 9 16]]


## Slicint e Iteración de matrices

In [44]:
a

array([10, 12, 14, 16, 18])

In [45]:
print(a[2:5]) # slice desde el elemento posición 2 hasta 5-1

[14 16 18]


In [48]:
print(a[3:])

[16 18]


In [49]:
# Si queremos iterar por cada elementos
for i in a:
  print(i)

10
12
14
16
18


In [50]:
# creamos un array multidimensional
C = np.arange(18).reshape(6,3) # cambiamos la forma a 6 filas, 3 cols
print(C)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [51]:
print(C[3][2]) # posición 3fila, 2col

11


In [52]:
print(C[3,2]) # es el equivalente del anterior

11


In [53]:
print(C[3][3])

IndexError: ignored

In [54]:
# Accedemos a la fila completa
print(C[2])

[6 7 8]


In [56]:
C

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [61]:
# Accedemos a la columna 1 (pos 0)
print(C[:,0]) # en este caso devolver todas las filas, columna pos 0

[ 0  3  6  9 12 15]


In [62]:
print(C[3:,1]) # devuelve las filas pos. 3 en adelante, columna pos. 1

[10 13 16]


In [63]:
# Extraemos todas las filas hasta la 5a
print(C[:5]) # todas las filas hasta las 5a - 1

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [65]:
C.shape

(6, 3)

In [64]:
# iteramos un array multidimensional
for i in range(C.shape[0]):
  for j in range(C.shape[1]):
    print("Elemento: {}".format(C[i, j]))

Elemento: 0
Elemento: 1
Elemento: 2
Elemento: 3
Elemento: 4
Elemento: 5
Elemento: 6
Elemento: 7
Elemento: 8
Elemento: 9
Elemento: 10
Elemento: 11
Elemento: 12
Elemento: 13
Elemento: 14
Elemento: 15
Elemento: 16
Elemento: 17


In [66]:
# Realizamos el cambio en bloque de una fila completa, por su posición
C[2] = [45, 46, 47]
C

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [45, 46, 47],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [70]:
# Cambio de todos los valores por N utilizamos [...]
D = C # copiamos la matriz 
D[...] = 1.5
D # devuelve valores enteros

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# Replicando el Juego de la vida de Conway 1970

https://es.wikipedia.org/wiki/Juego_de_la_vida

El juego de la vida es un ejemplo clásico de autómata celular creado en 1970 por el famoso matemático John H. Conway. 
En el problema clásico, se representan en una matriz bidimensional células que vivirán o morirán dependiendo del número de vecinos en un determinado paso de la simulación. Cada célula tiene 8 vecinos (las casillas adyacentes en un tablero bidimensional) y puede estar viva (1) o muerta (0). Las reglas clásicas entre transición vida/muerte son las siguientes:
Una célula muerta con exactamente 3 células vecinas vivas al turno siguiente estará viva.Una célula viva con 2 o 3 células vecinas vivas sigue viva. Si no es el caso, muere o permanece muerta (soledad en caso de un número menor a 2, superpoblación si es mayor a 3).
Este problema (o juego) tiene muchas variantes dependiendo de las condiciones iniciales, si el tablero (o mundo) tiene bordes o no, o si bien las reglas de vida o muerte son alteradas.A continuación tenéis un ejemplo del juego clásico implementado en NumPy:

In [71]:
SIZE = 10
STEPS = 10

In [73]:
def iterate(Z):
  # Contar vecinos
  N = (Z[0:-2,0:-2] + Z[0:-2, 1:-1] + Z[0:-2,2:] +
       Z[1:-1,0:-2]                + Z[1:-1,2:] +
       Z[2: ,0:-2]  + Z[2: ,1:-1] + Z[2: ,2:])
  
  # Aplicando las reglas
  birth = (N==3) & (Z[1:-1,1:-1]==0)
  survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
  Z[...] = 0
  Z[1:-1,1:-1][birth | survive] = 1
  return Z  

In [ ]:
np.random.randint()

In [84]:
N = (Z[0:-2,0:-2] + Z[0:-2, 1:-1] + Z[0:-2,2:] +
       Z[1:-1,0:-2]                + Z[1:-1,2:] +
       Z[2: ,0:-2]  + Z[2: ,1:-1] + Z[2: ,2:])

In [85]:
N

array([[2, 2, 2, 2, 2, 1, 0, 0],
       [3, 3, 4, 3, 3, 2, 0, 0],
       [5, 6, 7, 6, 5, 3, 0, 0],
       [5, 6, 6, 6, 5, 3, 0, 0],
       [4, 5, 6, 6, 5, 3, 0, 0],
       [3, 4, 5, 4, 4, 2, 0, 0],
       [2, 1, 3, 2, 3, 1, 0, 0],
       [1, 1, 2, 1, 1, 0, 0, 0]])

In [95]:
birth = (N==3) & (Z[1:-1,1:-1]==0)
birth

array([[False, False, False, False, False, False, False, False],
       [ True,  True, False,  True, False, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False,  True, False, False],
       [ True, False, False, False, False, False, False, False],
       [False, False,  True, False,  True, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [96]:
survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
survive

array([[ True,  True, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [88]:
# Creamos el tablero con células vivas o muertas de forma aleatoria
Z = np.random.randint(0,2,(SIZE, SIZE))

# Simulamos durante los pasos indicados
for i in range(STEPS):
  Z = iterate(Z)
  break
print(Z)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 1 0 0]
 [0 0 0 1 0 1 0 1 0 0]
 [0 1 1 1 0 0 0 1 0 0]
 [0 1 1 0 1 1 0 0 0 0]
 [0 0 0 1 0 1 0 1 1 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [89]:
Z

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [93]:
Z[1:-1,1:-1] == 0

array([[False, False,  True,  True,  True,  True, False,  True],
       [ True,  True, False,  True, False,  True, False,  True],
       [False, False, False,  True,  True,  True, False,  True],
       [False, False,  True, False, False,  True,  True,  True],
       [ True,  True, False,  True, False,  True, False, False],
       [ True,  True, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [97]:
print(Z[1:-1,1:-1])

[[1 1 0 0 0 0 1 0]
 [0 0 1 0 1 0 1 0]
 [1 1 1 0 0 0 1 0]
 [1 1 0 1 1 0 0 0]
 [0 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]]


## Prácticas con Numpy

### Ejercicio 1
Calculad la norma y el determinante de la siguiente matriz: ```[[1, 0], [2, -1]]```.

In [99]:
# Respuesta
A = np.array([
              [1,0],
              [2,-1]
])

In [101]:
# Calculamos la norma
norma = np.linalg.norm(A)
print(norma)

2.449489742783178


In [102]:
determ = np.linalg.det(A)
print(determ)

-1.0


## Ejercicio 2

Generad una lista de 100 valores enteros aleatorios de 0-9. Realizad los siguientes cálculos utilizando métodos de _numpy_:
- Media y desviación estándar de los valores de la lista
- Valor máximo y mínimo
- Sumad todos los valores de la lista
- Conseguid una lista de valores únicos

In [103]:
# Respuesta
from random import randint
import numpy as np

In [104]:
# Utilizamos la función randint para generar los valores aleatorios y los guardamos en una lista
rand_ints = [randint(0,9) for _ in range(100)]

In [105]:
# Para calcular la media y desviación
media = np.mean(rand_ints)
desv = np.std(rand_ints)

In [106]:
print("Nuestra lista de valores es {}".format(rand_ints))
print("Su valor medio es %f, y su desviación estándar es %f"%(media,desv))

Nuestra lista de valores es [6, 5, 0, 6, 4, 8, 2, 5, 4, 3, 5, 9, 7, 5, 4, 6, 7, 5, 6, 4, 6, 5, 0, 6, 8, 7, 8, 6, 5, 8, 1, 5, 5, 6, 4, 5, 7, 1, 9, 9, 6, 1, 9, 2, 0, 3, 5, 1, 1, 2, 0, 4, 0, 2, 6, 7, 5, 2, 8, 1, 7, 3, 5, 1, 9, 9, 2, 0, 1, 4, 0, 1, 2, 0, 1, 2, 4, 5, 1, 7, 5, 0, 2, 2, 0, 4, 6, 1, 4, 9, 0, 1, 6, 3, 5, 3, 8, 4, 8, 5]
Su valor medio es 4.170000, y su desviación estándar es 2.738814


In [107]:
# Valores máximo y mínimo
max_val = np.max(rand_ints)
min_val = np.min(rand_ints)

In [108]:
print(max_val)
print(min_val)

9
0


In [109]:
suma_valores = np.sum(rand_ints)
print(suma_valores)

417


In [110]:
valores_unicos = np.unique(rand_ints)
print(valores_unicos)

[0 1 2 3 4 5 6 7 8 9]


# Ejercicio 3 

Cread dos matrices de tamaño 5x5 con números reales aleatorios. Obtened el resultado de multiplicar ambas matrices usando los dos métodos de multiplicación de matrices vistos en el Notebook de teoría. ¿Cuál es la diferencia entre ambos resultados? Cread ahora dos matrices de tamaño 4x5 y 5x5 respectivamente, repetid la operación. Describid cuál de los métodos de multiplicación podéis aplicar y porqué. 

In [112]:
import numpy as np
B = np.random.rand(5,5)
C = np.random.rand(5,5)

In [114]:
print(B)
print("*"*10)
print(C)

[[0.46322367 0.03051328 0.19053438 0.45383339 0.70164884]
 [0.54753609 0.99204463 0.69015939 0.76088045 0.82443463]
 [0.39133426 0.82033244 0.8919286  0.32049189 0.41477312]
 [0.62471425 0.47326554 0.41500941 0.37851075 0.50697812]
 [0.78863641 0.81063137 0.07920411 0.10120406 0.74990838]]
**********
[[0.40074971 0.5940319  0.38323736 0.17322638 0.88748595]
 [0.17724904 0.92887162 0.2279166  0.32521007 0.62418004]
 [0.52038361 0.07293592 0.78969898 0.27574983 0.69934347]
 [0.98370253 0.27983683 0.03925332 0.89476941 0.83217984]
 [0.0138666  0.36767432 0.65205361 0.59278784 0.53862475]]


In [115]:
B*C

array([[0.18563675, 0.01812586, 0.07301989, 0.07861591, 0.62270349],
       [0.09705025, 0.9214821 , 0.15729878, 0.24744598, 0.51459564],
       [0.20364394, 0.0598317 , 0.70435511, 0.08837558, 0.29006887],
       [0.61453299, 0.13243713, 0.0162905 , 0.33867983, 0.42189697],
       [0.0109357 , 0.29804834, 0.05164533, 0.05999253, 0.40391921]])

In [116]:
B.dot(C)

array([[0.7463627 , 0.70238691, 0.81027103, 0.96471073, 1.31899567],
       [1.51432365, 1.81311923, 1.54840056, 1.77730931, 2.66505377],
       [1.08739543, 1.30168906, 1.32433108, 1.11315775, 1.97321719],
       [0.92957606, 1.1332963 , 1.02044614, 1.01577678, 1.72812212],
       [0.61089933, 1.53126717, 1.04249175, 0.95716949, 1.74941372]])

In [117]:
# creamos una matriz 4x5
D = np.random.rand(4,5)
D

array([[0.68430563, 0.87093145, 0.44454496, 0.5676491 , 0.49725536],
       [0.68920851, 0.98878951, 0.98469565, 0.63545953, 0.24869201],
       [0.83617636, 0.56986758, 0.02612753, 0.78397511, 0.51253143],
       [0.2934002 , 0.41402402, 0.50493042, 0.14785505, 0.5321755 ]])

In [118]:
E = np.random.rand(5,5)

In [119]:
D*E # es imposible por tener dos dimensiones diferentes

ValueError: ignored

In [120]:
D.dot(E) # es posible porque estamos realizando el producto de matrices

array([[1.51923562, 1.39790687, 1.56063744, 1.87834997, 1.05258996],
       [1.69592485, 1.73015479, 1.86960769, 2.12248096, 1.41066527],
       [1.51271957, 1.40922665, 1.55893136, 1.93309069, 0.75164899],
       [0.68227895, 0.71274036, 0.86312096, 0.9827057 , 0.89546708]])